//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpCompiler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpCompiler.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CSharpCompiler.Messages
        ///{
        ///    internal class BuildFailureMessage : BuildStatusMessage
        ///    {
        ///        public BuildFailureMessage(object value, string format) : base(&quot;FAILURE&quot;, value, format)
        ///        {
        ///
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string BuildFailureMessage {
            get {
                return ResourceManager.GetString("BuildFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CSharpCompiler.Messages
        ///{
        ///    internal class BuildNumberMessage : TeamCityServiceMessageSimple
        ///    {
        ///        public BuildNumberMessage(object buildNumber) : base(&quot;buildNumber&quot;, buildNumber)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string BuildNumberMessage {
            get {
                return ResourceManager.GetString("BuildNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace CSharpCompiler.Messages
        ///{
        ///    public class BuildStatisticMessage : TeamCityServiceMessageWithAttributes
        ///    {
        ///        private readonly object key;
        ///        private readonly int value;
        ///
        ///        public static readonly ISet&lt;string&gt; PredefinedStatisticsKeys = new HashSet&lt;string&gt;(StringComparer.InvariantCultureIgnoreCase)
        ///                                                                           {
        ///                                               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildStatisticMessage {
            get {
                return ResourceManager.GetString("BuildStatisticMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        ///namespace CSharpCompiler.Messages
        ///{
        ///    public class BuildStatusMessage : TeamCityServiceMessageWithAttributes
        ///    {
        ///        private readonly string status;
        ///        private readonly object value;
        ///        private readonly string format;
        ///
        ///        protected BuildStatusMessage(string status, object value, string format) : base(&quot;buildStatus&quot;)
        ///        {
        ///            this.status = status;
        ///            this.value = value;
        ///            this.format = format [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildStatusMessage {
            get {
                return ResourceManager.GetString("BuildStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CSharpCompiler.Messages
        ///{
        ///    internal class BuildSuccessMessage : BuildStatusMessage
        ///    {
        ///        public BuildSuccessMessage(object value, string format) : base(&quot;SUCCESS&quot;, value, format)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string BuildSuccessMessage {
            get {
                return ResourceManager.GetString("BuildSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CSharpCompiler.Messages
        ///{
        ///    internal class ProgressMessage : TeamCityServiceMessageSimple
        ///    {
        ///        public ProgressMessage(object value) : base(&quot;progressMessage&quot;, value)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string ProgressMessage {
            get {
                return ResourceManager.GetString("ProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CSharpCompiler.Messages
        ///{
        ///    internal class PublishArtifactsMessage : TeamCityServiceMessageSimple
        ///    {
        ///        public PublishArtifactsMessage(string artifact, params string[] targets) : base(&quot;publishArtifacts&quot;, Compute(artifact, targets))
        ///        {
        ///        }
        ///
        ///        private static object Compute(string artifact, params string[] targets)
        ///        {
        ///            var artifactSpecification = new StringBuilder(artifact);
        ///
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublishArtifactsMessage {
            get {
                return ResourceManager.GetString("PublishArtifactsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///
        ///namespace CSharpCompiler.Messages
        ///{
        ///    public abstract class TeamCityServiceMessage
        ///    {
        ///        protected TeamCityServiceMessage(string name)
        ///        {
        ///            Name = name;
        ///        }
        ///
        ///        private string Name { get; set; }
        ///
        ///        public void Run(TextWriter outputWriter)
        ///        {
        ///            outputWriter.WriteLine(String.Format(&quot;##teamcity[{0}{1}]&quot;, Name, FormattedAndEscapedValue));
        ///        }
        ///
        ///        protected abstract string FormattedAndEscape [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamCityServiceMessage {
            get {
                return ResourceManager.GetString("TeamCityServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///
        ///namespace CSharpCompiler.Messages
        ///{
        ///    public static class TeamCityServiceMessagesExtensions
        ///    {
        ///        static TeamCityServiceMessagesExtensions()
        ///        {
        ///            OutputWriter = Console.Out;
        ///        }
        ///
        ///        public static TextWriter OutputWriter { get; set; }
        ///
        ///        public static T Failure&lt;T&gt;(this T value, string format)
        ///        {
        ///            Run(new BuildFailureMessage(value, format));
        ///
        ///            return value;
        ///        }
        ///
        ///        private s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamCityServiceMessagesExtensions {
            get {
                return ResourceManager.GetString("TeamCityServiceMessagesExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CSharpCompiler.Messages
        ///{
        ///    internal abstract class TeamCityServiceMessageSimple : TeamCityServiceMessage
        ///    {
        ///        private readonly object value;
        ///
        ///        protected TeamCityServiceMessageSimple(string name, object value) : base(name)
        ///        {
        ///            this.value = value;
        ///        }
        ///
        ///        protected override string FormattedAndEscapedValue
        ///        {
        ///            get { return &quot; &apos;&quot; + Escape(value) + &quot;&apos;&quot;; }
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string TeamCityServiceMessageSimple {
            get {
                return ResourceManager.GetString("TeamCityServiceMessageSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace CSharpCompiler.Messages
        ///{
        ///    public abstract class TeamCityServiceMessageWithAttributes : TeamCityServiceMessage
        ///    {
        ///        protected TeamCityServiceMessageWithAttributes(string name) : base(name)
        ///        {
        ///        }
        ///
        ///        protected override string FormattedAndEscapedValue
        ///        {
        ///            get
        ///            {
        ///                return Properties.Aggregate(new StringBuilder(),
        ///                           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamCityServiceMessageWithAttributes {
            get {
                return ResourceManager.GetString("TeamCityServiceMessageWithAttributes", resourceCulture);
            }
        }
    }
}
